/**********************************************************************************************************************
 * \file ADC_Group_Scan.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "ADC_Group_Scan.h"
#include "ASCLIN_UART.h"
#include "GTM_TOM_PWM.h"


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

IfxVadc_Adc g_vadc;                             /* Handle for VADC registers                                        */
IfxVadc_Adc_Group g_adcGroup;                   /* Handle for the VADC group registers                              */
IfxVadc_Adc_Channel g_adcChannel[N_CHANNELS];   /* Handle for the VADC channel registers                            */
/* Define the used channels */
IfxVadc_ChannelId g_vadcChannelIDs[] = {IfxVadc_ChannelId_0};  /* AN36: channel 0 of group 0                         */
//                                        IfxVadc_ChannelId_1,  /* AN37: channel 1 of group 0                         */
//                                        IfxVadc_ChannelId_2,  /* AN38: channel 2 of group 0                         */
//                                        IfxVadc_ChannelId_3}; /* AN39: channel 3 of group 0                         */



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Configuration and initialization of the VADC module and the group(s) that will be used */
//ADC初始化
void init_vadc(void)
{
    /* Create and initialize the module configuration */
    IfxVadc_Adc_Config adcConf;                             /* Define a configuration structure for the VADC module */
    IfxVadc_Adc_initModuleConfig(&adcConf, &MODULE_VADC);   /* Fill it with default values                          */

    IfxVadc_Adc_initModule(&g_vadc, &adcConf);              /* Apply the configuration to the module                */

    /* Create and initialize the group configuration */
    IfxVadc_Adc_GroupConfig adcGroupConf;                   /* Define a configuration structure for the VADC group  */
    IfxVadc_Adc_initGroupConfig(&adcGroupConf, &g_vadc);    /* Fill it with default values                          */

    /* Configuration of the group */
    adcGroupConf.groupId = IfxVadc_GroupId_0;               /* Select the group                                     */
    adcGroupConf.master = adcGroupConf.groupId;             /* Select the master group                              */

    adcGroupConf.arbiter.requestSlotScanEnabled = TRUE;     /* Enable scan source                                   */
    adcGroupConf.scanRequest.autoscanEnabled = TRUE;        /* Enable auto scan mode                                */

    /* Enable all gates in "always" mode (no edge detection) */
    adcGroupConf.scanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always;

    IfxVadc_Adc_initGroup(&g_adcGroup, &adcGroupConf);      /* Apply the configuration to the group                 */

    /* Create and initialize the channels configuration */
    uint32 chnIx;

    /* Create channel configuration */
    IfxVadc_Adc_ChannelConfig adcChannelConf[N_CHANNELS]; /* Define a configuration structure for the VADC channels */

    for(chnIx = 0; chnIx < N_CHANNELS; ++chnIx)
    {
        IfxVadc_Adc_initChannelConfig(&adcChannelConf[chnIx], &g_adcGroup);     /* Fill it with default values      */

        adcChannelConf[chnIx].channelId = g_vadcChannelIDs[chnIx];              /* Select the channel ID            */
        adcChannelConf[chnIx].resultRegister = (IfxVadc_ChannelResult)(chnIx);  /* Use dedicated result register    */

        /* Initialize the channel */
        IfxVadc_Adc_initChannel(&g_adcChannel[chnIx], &adcChannelConf[chnIx]);

        /* Add the channel to the scan sequence */
        uint32 enableChnBit = (1 << adcChannelConf[chnIx].channelId);   /* Set the the corresponding input channel  */
        uint32 mask = enableChnBit;                                     /* of the respective group to take part in  */
        IfxVadc_Adc_setScan(&g_adcGroup, enableChnBit, mask);           /* the background scan sequence.            */
    }

    /* Start the scan */
    IfxVadc_Adc_startScan(&g_adcGroup);
}

/* Get and print VADC conversions */
void run_vadc(void)
{
    uint32 chnIx;

    /* Get the VADC conversions */
    for(chnIx = 0; chnIx < N_CHANNELS; ++chnIx)   //每个通道依次计算得到ADC的数字量
    {
        Ifx_VADC_RES conversionResult;

        /* Wait for a new valid result */
        do
        {
            conversionResult = IfxVadc_Adc_getResult(&g_adcChannel[chnIx]);
        } while(!conversionResult.B.VF); /* B for Bitfield access, VF for Valid Flag */

        /* Print the conversion to the UART */
        send_vadc(chnIx, conversionResult.B.RESULT);

    }
}

/* Print, via UART, the VADC results after conversions */
void send_vadc(uint32 chnIx, uint32 adcVal)
{
    char str[TX_LENGTH] = {'C','h','.','X',':',' ','X','X','X','X',' ',' ','V',':','X','.','X','X','X','\n','\r'};  /* X to be replaced by correct values*/
    uint32 num = 0, num0 = 0;
    num0 = adcVal * pwm_data;
    num = adcVal * change_data;

    if (num0 >= 50000)  //50000是周期
    {
        num0 = 0;

    }
    else
    {
        num0 = 50000 - num0;
    }
    setDutyCycle(1, num0);  //设置LED灯的占空比
    num0 = 50000 - num0;
    if (num0 < 5)
    {
        num = 0;
    }
    setDutyCycle(2, num0);  //设置LED2灯的占空比，由于和LED灯的占空比相反
    str[3] = (char) chnIx + ASCII_SHIFT;                                        /* Channel index                    */

    /* Turns the digital converted value into its ASCII characters, e.g. 1054 -> '1','0','5','4' */
    /* 12-bits range value: 0-4095*/
    //打印输出此时测量的数字量和转换得到的电压值
    str[6] = (adcVal / 1000) + ASCII_SHIFT;                                     /* Thousands                        */
    str[7] = ((adcVal % 1000) / 100) + ASCII_SHIFT;                             /* Hundreds                         */
    str[8] = ((adcVal % 100) / 10) + ASCII_SHIFT;                               /* Tens                             */
    str[9] = (adcVal % 10) + ASCII_SHIFT;                                       /* Units                            */
    //此时的电压值
    str[14] = (num / 1000) + ASCII_SHIFT;                                     /* Thousands                        */
    str[16] = ((num % 1000) / 100) + ASCII_SHIFT;                             /* Hundreds                         */
    str[17] = ((num % 100) / 10) + ASCII_SHIFT;                               /* Tens                             */
    str[18] = (num % 10) + ASCII_SHIFT;                                       /* Units                            */

    /* Print via UART */
    //串口发送
    send_data(str, TX_LENGTH);
}






